"use client";

import Link from "next/link";

export default function About() {
  return (
      <section className="bg-white py-20 lg:py-28">
            <div className="max-w-7xl mx-auto px-5 lg:px-8">

                    <div className="grid lg:grid-cols-2 gap-16 items-center">

                              {/* Left Content */}
                                        <div className="order-2 lg:order-1">

                                                    <div className="flex items-center gap-3 mb-5">
                                                                  <div className="w-10 h-[3px] bg-[#C61F26]" />
                                                                                <span className="text-[#C61F26] font-semibold uppercase tracking-wide">
                                                                                                About Company
                                                                                                              </span>
                                                                                                                          </div>

                                                                                                                                      <h2 className="text-4xl lg:text-6xl font-extrabold text-[#111827] leading-tight">
                                                                                                                                                    Building Beautiful
                                                                                                                                                                  <br />
                                                                                                                                                                                Spaces Since 2006
                                                                                                                                                                                            </h2>

                                                                                                                                                                                                        <p className="mt-8 text-gray-600 text-lg leading-9">
                                                                                                                                                                                                                      Sai Lalit Interior, Exterior & Co. has been delivering premium
                                                                                                                                                                                                                                    interior and exterior solutions for over 20 years. With 170+
                                                                                                                                                                                                                                                  successful projects, we combine innovative designs, quality
                                                                                                                                                                                                                                                                materials and skilled craftsmanship to create spaces that are
                                                                                                                                                                                                                                                                              functional, elegant and built to last.
                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                      <div className="grid sm:grid-cols-2 gap-y-5 gap-x-10 mt-10">

                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                    <span className="w-6 h-6 rounded-full bg-[#C61F26] text-white flex items-center justify-center text-sm">
                                                                                                                                                                                                                                                                                                                                                      ✓
                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                      <span className="font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                        20+ Years of Experience
                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="w-6 h-6 rounded-full bg-[#C61F26] text-white flex items-center justify-center text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ✓
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Imported Aluminium Specialists
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="w-6 h-6 rounded-full bg-[#C61F26] text-white flex items-center justify-center text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ✓
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        170+ Projects Completed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="w-6 h-6 rounded-full bg-[#C61F26] text-white flex items-center justify-center text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ✓
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="font-medium">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Premium Quality Materials
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href="/about"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="inline-flex items-center gap-3 mt-12 bg-[#C61F26] hover:bg-red-700 text-white px-8 py-4 rounded-lg font-semibold text-lg transition-all duration-300 shadow-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Explore More About Us
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>→</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Right Image */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="order-1 lg:order-2">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      src="https://lookuptrendz.com/wp-content/uploads/2026/07/file_0000000005cc7207a29e43efa21b3c3d.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alt="Sai Lalit Interior"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full h-[350px] lg:h-[560px] object-cover rounded-3xl shadow-2xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }