"use client";

import Link from "next/link";

export default function Hero() {
  return (
      <section
            className="relative min-h-screen bg-cover bg-center"
                  style={{
                          backgroundImage:
                                    "url('https://lookuptrendz.com/wp-content/uploads/2026/07/file_0000000005cc7207a29e43efa21b3c3d.png')",
                                          }}
                                              >
                                                    {/* Dark Overlay */}
                                                          <div className="absolute inset-0 bg-black/55"></div>

                                                                <div className="relative z-10 max-w-7xl mx-auto px-6 lg:px-8 pt-36 lg:pt-44 pb-36">

                                                                        <div className="max-w-2xl">

                                                                                  <h1 className="text-white font-extrabold leading-tight text-5xl lg:text-7xl">

                                                                                              Transforming Spaces
                                                                                                          <br />

                                                                                                                      with Premium
                                                                                                                                  <br />

                                                                                                                                              <span className="text-[#C61F26]">
                                                                                                                                                            Interior & Exterior
                                                                                                                                                                        </span>

                                                                                                                                                                                    <br />

                                                                                                                                                                                                Solutions

                                                                                                                                                                                                          </h1>

                                                                                                                                                                                                                    <h2 className="mt-8 text-white text-2xl lg:text-4xl font-semibold">

                                                                                                                                                                                                                                Building Dream Homes &
                                                                                                                                                                                                                                            Commercial Spaces

                                                                                                                                                                                                                                                        <span className="text-[#C61F26]">
                                                                                                                                                                                                                                                                      {" "}
                                                                                                                                                                                                                                                                                    Since 2006
                                                                                                                                                                                                                                                                                                </span>

                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                    <p className="mt-8 text-white/90 leading-8 text-lg">

                                                                                                                                                                                                                                                                                                                                With over 20 years of experience and 170+
                                                                                                                                                                                                                                                                                                                                            completed projects, Sai Lalit Interior,
                                                                                                                                                                                                                                                                                                                                                        Exterior & Co. specializes in imported
                                                                                                                                                                                                                                                                                                                                                                    aluminium systems, modular interiors,
                                                                                                                                                                                                                                                                                                                                                                                false ceilings, ACP cladding,
                                                                                                                                                                                                                                                                                                                                                                                            elevations, railings and customized
                                                                                                                                                                                                                                                                                                                                                                                                        design solutions across
                                                                                                                                                                                                                                                                                                                                                                                                                    Visakhapatnam, Vizianagaram
                                                                                                                                                                                                                                                                                                                                                                                                                                and Hyderabad.

                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-10 flex flex-col sm:flex-row gap-5">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href="https://wa.me/918106406999"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="bg-[#C61F26] hover:bg-red-700 transition-all duration-300 px-8 py-4 rounded-md text-white font-semibold text-lg text-center shadow-xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    📋 Get Free Quote
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="/projects"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="border-2 border-white hover:bg-white hover:text-black transition-all duration-300 px-8 py-4 rounded-md text-white font-semibold text-lg text-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  View Our Projects →
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            