export default function Stats() {
        return (
            <section className="relative -mt-20 z-20 px-5 lg:px-8">
                  <div className="max-w-7xl mx-auto bg-[#161616] rounded-2xl shadow-2xl">

                          <div className="grid grid-cols-2 lg:grid-cols-4">

                                    <div className="flex flex-col items-center p-8 border-b lg:border-b-0 lg:border-r border-gray-700">
                                                <img
                                                              src="https://lookuptrendz.com/wp-content/uploads/2026/07/1_20260705_163956_0000.png"
                                                                            alt="Experience"
                                                                                          className="w-14 h-14 mb-4"
                                                                                                      />
                                                                                                                  <h3 className="text-white text-3xl font-bold">20+</h3>
                                                                                                                              <p className="text-gray-300 text-center">
                                                                                                                                            Years of Experience
                                                                                                                                                        </p>
                                                                                                                                                                  </div>

                                                                                                                                                                            <div className="flex flex-col items-center p-8 border-b lg:border-b-0 lg:border-r border-gray-700">
                                                                                                                                                                                        <img
                                                                                                                                                                                                      src="https://lookuptrendz.com/wp-content/uploads/2026/07/2_20260705_163956_0001.png"
                                                                                                                                                                                                                    alt="Projects"
                                                                                                                                                                                                                                  className="w-14 h-14 mb-4"
                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                          <h3 className="text-white text-3xl font-bold">170+</h3>
                                                                                                                                                                                                                                                                      <p className="text-gray-300 text-center">
                                                                                                                                                                                                                                                                                    Projects Completed
                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                    <div className="flex flex-col items-center p-8 border-b lg:border-b-0 lg:border-r border-gray-700">
                                                                                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                                                                                              src="https://lookuptrendz.com/wp-content/uploads/2026/07/3_20260705_163957_0002.png"
                                                                                                                                                                                                                                                                                                                                                            alt="Aluminium"
                                                                                                                                                                                                                                                                                                                                                                          className="w-14 h-14 mb-4"
                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-white text-3xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                Imported
                                                                                                                                                                                                                                                                                                                                                                                                                            </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-gray-300 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Aluminium Specialists
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex flex-col items-center p-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                src="https://lookuptrendz.com/wp-content/uploads/2026/07/4_20260705_163957_0003.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alt="Serving"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-14 h-14 mb-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-white text-3xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Serving
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-300 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Vizag • Vizianagaram • Hyderabad
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }